--- #EC2 module - provision example
- hosts: localhost
  remote_user: test
  become: yes
  gather_facts: no
  connection: local
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Provision aws linux ami
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ region }}"
      image: ami-f9dd458a
      instance_type: t2.micro
      count: 1
      vpc_subnet_id: subnet-566ad60f
      assign_public_ip: yes
