--- #Create AMI from EC2
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  remote_user: test
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create AMI from EC2 Instance ID
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ region }}"
      instance_id: i-0297d7d5a0e46c755
      wait: no
      name: jb-ansible-test-ami
      tags:
        Name: JB-Web-Server
        Service: JBWebServer
    register: instance
